namespace EDocument_Data.Consts.Enums
{
    public enum Governorate
    {
        Alexandria,
        Aswan,
        Asyut,
        Beheira,
        BeniSuef,
        Cairo,
        Damietta,
        Dakahlia,
        Fayoum,
        Gharbia,
        Giza,
        Ismailia,
        KafrElSheikh,
        Luxor,
        Matrouh,
        Menofia,
        Minya,
        Monufia,
        NorthSinai,
        PortSaid,
        Qalyubia,
        Qena,
        RedSea,
        Sharqia,
        Sohag,
        SouthSinai,
        Suez,
    }
}