// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class DefinedRequestRoleConfiguration : IEntityTypeConfiguration<DefinedRequestRole>
    {
        public void Configure(EntityTypeBuilder<DefinedRequestRole> entity)
        {

            entity.ToTable(nameof(DefinedRequestRole));

            entity.HasKey(e => new { e.RoleId, e.DefinedRequestId ,e.Permission});
      

            entity.Property(e => e.RoleId)
            .HasMaxLength(450);

            entity.Property(e => e.Permission)
            .HasConversion<string>()
            .HasMaxLength(450);

            entity.Property(e => e.CreatedAt)
           .HasColumnType("smalldatetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);


            entity.HasOne(d => d.DefinedRequest).WithMany(p => p.DefinedRequestRoles)
            .HasForeignKey(d => d.DefinedRequestId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestRole_DefinedRequest");

            entity.HasOne(d => d.Role).WithMany(p => p.DefinedRequestRoles)
            .HasForeignKey(d => d.RoleId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestRole_Role");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DefinedRequestRole> entity);
    }
}
