// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class DefinedRequestReviewerConfiguration : IEntityTypeConfiguration<DefinedRequestReviewer>
    {
        public void Configure(EntityTypeBuilder<DefinedRequestReviewer> entity)
        {
            entity.HasKey(e => new { e.DefinedRequestId, e.ReviewerId });

            entity.ToTable("DefinedRequestReviewer");


            entity.Property(e => e.ReviewerId)
            .HasMaxLength(50);

            entity.Property(e => e.StageName)
            .HasMaxLength(50);

            entity.Property(e => e.CreatedAt)
            .HasColumnType("datetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("datetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);

            entity.HasOne(d => d.DefinedRequest).WithMany(p => p.DefinedRequestReviewers)
            .HasForeignKey(d => d.DefinedRequestId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestReviewer_DefinedRequest");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.DefinedRequestReviewers)
            .HasForeignKey(d => d.ReviewerId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestReviewer_User");

            entity.HasOne(d => d.RequestedApplication).WithMany(p => p.DefinedRequestReviewers)
            .HasForeignKey(d => d.RequestedApplicationId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestReviewer_EmployeeRequestedApplication");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DefinedRequestReviewer> entity);
    }
}
