// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class DefinedRequestRoleConfiguration : IEntityTypeConfiguration<DefinedRequestRole>
    {
        public void Configure(EntityTypeBuilder<DefinedRequestRole> entity)
        {
            entity.ToTable("DefinedRequestRole");

            entity.Property(e => e.Id)
            .ValueGeneratedNever();

            entity.Property(e => e.RoleName)
            .IsRequired()
            .HasMaxLength(50);

            entity.Property(e => e.CreatedAt)
            .HasColumnType("datetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("datetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);

            entity.HasOne(d => d.DefinedRequest).WithMany(p => p.DefinedRequestRoles)
            .HasForeignKey(d => d.DefinedRequestId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestRole_DefinedRequest");

            entity.HasOne(d => d.RequestedApplication).WithMany(p => p.DefinedRequestRoles)
            .HasForeignKey(d => d.RequestedApplicationId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedRequestRole_RequestedApplication");

            entity.HasMany(d => d.Requests).WithMany(p => p.RequestedRoles)
            .UsingEntity<Dictionary<string, object>>(
                "RequestRole",
                r => r.HasOne<Request>().WithMany()
                    .HasForeignKey("RequestId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_RequestRole_Request"),
                l => l.HasOne<DefinedRequestRole>().WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_RequestRole_DefinedRequestRole"),
                j =>
                {
                    j.HasKey("RoleId", "RequestId");
                    j.ToTable("RequestRole");
                    j.IndexerProperty<long>("RoleId");
                    j.IndexerProperty<long>("RequestId");
                });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DefinedRequestRole> entity);
    }
}
