// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class DefinedApplicationRoleConfiguration : IEntityTypeConfiguration<DefinedApplicationRole>
    {
        public void Configure(EntityTypeBuilder<DefinedApplicationRole> entity)
        {
            entity.ToTable(nameof(DefinedApplicationRole));

            entity.Property(e => e.Id)
            .UseIdentityColumn();

            entity.Property(e => e.RoleName)
            .IsRequired()
            .HasMaxLength(50);

            entity.Property(e => e.CreatedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);

            entity.HasOne(d => d.RequestedApplication).WithMany(p => p.DefinedApplicationRoles)
            .HasForeignKey(d => d.RequestedApplicationId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_DefinedApplicationRole_RequestedApplication");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DefinedApplicationRole> entity);
    }
}
