// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using EDocument_Data.Models.Audit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class PmJpRequestConfiguration : IEntityTypeConfiguration<PmJpRequest>
    {
        public void Configure(EntityTypeBuilder<PmJpRequest> entity)
        {

            entity.ToTable(nameof(PmJpRequest), tb => tb.HasTrigger($"TR_{nameof(AuditPmJpRequest)}"));

            entity.HasKey(e => e.RequestNumber);

            entity.Property(e => e.RequestNumber)
            .HasMaxLength(50)
            .ValueGeneratedNever();

            entity.Property(e => e.ChangeType)
            .IsRequired()
            .HasMaxLength(50);

            entity.Property(e => e.PmJpCode)
            .HasMaxLength(50);

            entity.Property(e => e.AssetType)
            .HasMaxLength(50);

            entity.Property(e => e.AssetCode)
            .HasMaxLength(50);

            entity.Property(e => e.CurrentInterval)
            .HasMaxLength(50);

            entity.Property(e => e.NewInterval)
            .HasMaxLength(50);

            entity.Property(e => e.AddedMaterials)
            .HasMaxLength(500);

            entity.Property(e => e.RemovedMaterials)
            .HasMaxLength(500);

            entity.Property(e => e.AddedLaborCraft)
            .HasMaxLength(500);

            entity.Property(e => e.RemovedLaborCraft)
            .HasMaxLength(500);

            entity.Property(e => e.AddedMeter)
            .HasMaxLength(500);

            entity.Property(e => e.RemovedMeter)
            .HasMaxLength(500);

           

            entity.Property(e => e.StartDate)
            .IsRequired()
            .HasColumnType("smalldatetime");

            entity.Property(e => e.EndDate)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(200);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(200);

            entity.HasOne(d => d.Request).WithOne(p => p.PmJpRequest)
            .HasForeignKey<PmJpRequest>(d => d.RequestId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_PmJpRequest_Request");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PmJpRequest> entity);
    }
}
