// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class RequestedApplicationConfiguration : IEntityTypeConfiguration<RequestedApplication>
    {
        public void Configure(EntityTypeBuilder<RequestedApplication> entity)
        {
            entity.ToTable("RequestedApplication");

            entity.Property(e => e.Id)
            .ValueGeneratedNever();

            entity.Property(e => e.ApplicationName)
            .IsRequired()
            .HasMaxLength(200);

            entity.Property(e => e.ApplicationOwnerId)
            .IsRequired()
            .HasMaxLength(50);

            entity.Property(e => e.CreatedAt)
            .HasColumnType("datetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("datetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);


            entity.HasOne(d => d.ApplicationOwner).WithMany(p => p.RequestedApplications)
            .HasForeignKey(d => d.ApplicationOwnerId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_RequestedApplication_User");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RequestedApplication> entity);
    }
}
