// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class RequestReviewerConfiguration : IEntityTypeConfiguration<RequestReviewer>
    {
        public void Configure(EntityTypeBuilder<RequestReviewer> entity)
        {
            entity.HasKey(e => new { e.RequestId, e.AssignedReviewerId });

            entity.ToTable(nameof(RequestReviewer));


            entity.Property(e => e.AssignedReviewerId)
            .HasMaxLength(50);


            entity.Property(e => e.ReviewerType).HasConversion<string>()
            .HasMaxLength(50);

            entity.Property(e => e.Status).HasConversion<string>()
            .HasMaxLength(50);


            entity.Property(e => e.CreatedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);

            entity.HasOne(d => d.Request).WithMany(p => p.RequestReviewers)
            .HasForeignKey(d => d.RequestId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_RequestReviewer_Request");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.RequestReviewers)
            .HasForeignKey(d => d.AssignedReviewerId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_RequestReviewer_User");



            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RequestReviewer> entity);
    }
}
