// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class RequestApplicationRoleConfiguration : IEntityTypeConfiguration<RequestApplicationRole>
    {
        public void Configure(EntityTypeBuilder<RequestApplicationRole> entity)
        {
            entity.ToTable(nameof(RequestApplicationRole));

            entity.HasKey(e=> new  {e.RequestId, e.ApplicationId,e.RoleId });

            entity.Property(e => e.CreatedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(50);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(50);

            entity.HasOne(e => e.Request)
            .WithMany(p => p.RequestApplicationRoles)
            .HasForeignKey(e => e.RequestId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_RequestApplicationRole_Request");

            entity.HasOne(e => e.Application)
            .WithMany(p=>p.RequestApplicationRoles)
            .HasForeignKey(e => e.ApplicationId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_RequestApplicationRole_DefinedApplication");

            entity.HasOne(e => e.Role)
            .WithMany(p => p.RequestApplicationRoles)
            .HasForeignKey(e => e.RoleId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_RequestApplicationRole_DefinedApplicationRole");



            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RequestApplicationRole> entity);
    }
}
