// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Azure;
using EDocument_Data.Consts.Enums;
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class TravelDeskRequestConfiguration : IEntityTypeConfiguration<TravelDeskRequest>
    {
        public void Configure(EntityTypeBuilder<TravelDeskRequest> entity)
        {
            entity.HasKey(e => e.RequestNumber);

            entity.ToTable(nameof(TravelDeskRequest));

            entity.Property(e => e.RequestNumber)
            .HasMaxLength(50)
            .ValueGeneratedNever();

            entity.Property(e => e.BeneficiaryId)
            .IsRequired()
            .HasMaxLength(50);

            entity.Property(e => e.BeneficiaryDepartment)
            .HasMaxLength(200);

            entity.Property(e => e.BeneficiaryEmail)
            .HasMaxLength(50);

            entity.Property(e => e.BeneficiaryName)
            .IsRequired()
            .HasMaxLength(200);

            entity.Property(e => e.BeneficiaryPosition)
            .HasMaxLength(200);

            entity.Property(e => e.BeneficiaryPhoneNumber)
            .HasMaxLength(50);

            entity.Property(e => e.BeneficiaryExtention)
            .HasMaxLength(50);

            entity.Property(e => e.BeneficiaryNationality)
            .IsRequired()
            .HasMaxLength(50);

            entity.Property(item => item.RequestType)

            .IsRequired()
            .HasMaxLength(200);
          

            entity.Property(e => e.PaymentMethod)
            .HasMaxLength(50);


            entity.Property(e => e.CostAllocation)
            .IsRequired();


            entity.Property(e => e.FlightOrigin)
            .HasMaxLength(50);

            entity.Property(e => e.FlightDestination)
            .HasMaxLength(50);

            entity.Property(e => e.DestinationCountry)
            .HasMaxLength(50);

            entity.Property(e => e.CheckIn)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CheckOut)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.DepartureDate)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ReturnDate)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ExpectedTravelTime)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.ModifiedAt)
            .HasColumnType("smalldatetime");

            entity.Property(e => e.CreatedBy)
            .HasMaxLength(200)
            .IsUnicode(false);

            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(200)
            .IsUnicode(false);

            entity.HasOne(d => d.Request).WithOne(p => p.TravelDeskRequest)
            .HasForeignKey<TravelDeskRequest>(d => d.RequestId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_TravelDeskRequest_Request");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TravelDeskRequest> entity);
    }
}
