// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDocument_Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EDocument_EF.Configurations
{
    public partial class VoucherRequestConfiguration : IEntityTypeConfiguration<VoucherRequest>
    {
        public void Configure(EntityTypeBuilder<VoucherRequest> entity)
        {
            //entity.HasKey(e => new { e.RequesterId, e.RequestId });

            //entity.ToTable("OracleAccessRequest");

            //entity.Property(e => e.RequesterId)
            //.HasMaxLength(50)
            //.IsUnicode(false);
            //entity.Property(e => e.RequestId);
            //entity.Property(e => e.RequesterDepartment)
            //.HasMaxLength(200)
            //.IsUnicode(false);
            //entity.Property(e => e.RequesterEmail)
            //.IsRequired()
            //.HasMaxLength(50)
            //.IsUnicode(false);
            //entity.Property(e => e.RequesterExtention);
            //entity.Property(e => e.RequesterName)
            //.IsRequired()
            //.HasMaxLength(200);
            //entity.Property(e => e.RequesterPostion)
            //.HasMaxLength(200)
            //.IsUnicode(false);

            //entity.Property(e => e.CreatedAt)
            //.HasColumnType("datetime");

            //entity.Property(e => e.ModifiedAt)
            //.HasColumnType("datetime");

            //entity.Property(e => e.CreatedBy)
            //.HasMaxLength(50)
            //.IsUnicode(false);

            //entity.Property(e => e.ModifiedBy)
            //.HasMaxLength(50)
            //.IsUnicode(false);

            //entity.HasOne(d => d.Request).WithMany(p => p.OracleAccessRequests)
            //.HasForeignKey(d => d.RequestId)
            //.OnDelete(DeleteBehavior.Restrict)
            //.HasConstraintName("FK_OracleAccessRequest_Request");

            //OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VoucherRequest> entity);
    }
}
