// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace EDocument_Data.Models;

public partial class ApplicationUser:IdentityUser
{
    public override string UserName { get; set; }

    public override string NormalizedUserName { get; set; }

    public override string Email => UserName!=null? $"{UserName}@dpwsapps.com":"";

    public string FullName { get; set; }

    public string Position { get; set; }

    public string DepartmentName { get; set; }

    public long DepartmentId { get; set; }

    public string ManagerId { get; set; }

    public string Company { get; set; }

    public virtual ICollection<DefinedRequestReviewer> DefinedRequestReviewers { get; set; } = new HashSet<DefinedRequestReviewer>();

    public virtual Department Department{ get; set; }

    public virtual ICollection<Department> ManagedDepartments { get; set; } = new HashSet<Department>();

    public virtual ICollection<ApplicationUser> ManagedEmployees { get; set; } = new HashSet<ApplicationUser>();

    public virtual ApplicationUser Manager { get; set; }

    public virtual ICollection<Request> CreatedRequests { get; set; } = new HashSet<Request>();

    public virtual ICollection<Request> ReviewingRequests { get; set; } = new HashSet<Request>();

    public virtual ICollection<RequestedApplication> RequestedApplications { get; set; } = new HashSet<RequestedApplication>();

    public DateTime? CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

}