// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public  class DefinedRequest: BaseEntity
{
    public long Id { get; set; }

    public string RequestName { get; set; }

    public string RouteName { get; set; }

    public int ReviewersNumber { get; set; }

    public long DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<DefinedRequestReviewer> DefinedRequestReviewers { get; set; } = new HashSet<DefinedRequestReviewer>();

    public virtual ICollection<Request> Requests { get; set; } = new HashSet<Request>();

    public virtual ICollection<DefinedRequestRole> DefinedRequestRoles { get; set; } = new HashSet<DefinedRequestRole>();
}