// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public  class DefinedApplicationRole : BaseEntity
{
    public long Id { get; set; }

    public string RoleName { get; set; }

    public long RequestedApplicationId { get; set; }

    public virtual DefinedApplication RequestedApplication { get; set; }

    public virtual ICollection<RequestApplicationRole> RequestApplicationRoles { get; set; } = new HashSet<RequestApplicationRole>();


}