// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public  class DefinedRequest: BaseEntity
{
    public long Id { get; set; }

    public string RequestName { get; set; }

    public bool DeptMgrApprove { get; set; }

    public bool DirectMgrApprove { get; set; }

    public int StagesNumber { get; set; }

    public virtual ICollection<DefinedRequestReviewer> DefinedRequestReviewers { get; set; } = new HashSet<DefinedRequestReviewer>();

    public virtual ICollection<DefinedRequestRole> DefinedRequestRoles { get; set; } = new HashSet<DefinedRequestRole>();

    public virtual ICollection<Request> Requests { get; set; } = new HashSet<Request>();
}