// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using EDocument_Data.Consts.Enums;
using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public  class DefinedRequestRole: BaseEntity
{
    public string RoleId { get; set; }
    public long DefinedRequestId { get; set; }
    public Permission Permission { get; set; }

    public Role Role { get; set; }

    public DefinedRequest DefinedRequest { get; set; }
}