// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public  class DefinedRequestRole : BaseEntity
{
    public long Id { get; set; }

    public string RoleName { get; set; }
    
    public long DefinedRequestId { get; set; }

    public virtual DefinedRequest DefinedRequest { get; set; }

    public long RequestedApplicationId { get; set; }

    public virtual RequestedApplication RequestedApplication { get; set; }

    public virtual ICollection<Request> Requests { get; set; } = new HashSet<Request>();
}