// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public class Department :BaseEntity
{
    public long Id { get; set; }

    public string DepartmentName { get; set; }

    public string ManagerId { get; set; }

    public virtual ICollection<User> Employees { get; set; } = new HashSet<User>();
    public virtual ICollection<Section> Sections { get; set; } = new HashSet<Section>();

    public virtual User Manager { get; set; }

    public virtual ICollection<DefinedRequest> DefinedRequests { get; set; } = new HashSet<DefinedRequest>();

    

}