// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using EDocument_Data.Models.Shared;

namespace EDocument_Data.Models;

public partial class Request : BaseEntity
{
    public long Id { get; set; }

    public int? CurrentStage { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }

    public string ReviewerNotes { get; set; }

    public string CreatorId { get; set; }

    public long? DefinedRequestId { get; set; }

    public virtual ApplicationUser Creator { get; set; }

    public virtual DefinedRequest DefinedRequest { get; set; }

    public virtual ICollection<ApplicationUser> Reviewers { get; set; } = new HashSet<ApplicationUser>();

    public virtual ICollection<DefinedRequestRole> RequestedRoles { get; set; } = new HashSet<DefinedRequestRole>();


    //public virtual ICollection<VoucherRequest> VoucherRequests { get; set; } = new HashSet<VoucherRequest>();
    //public virtual ICollection<PoRequest> PoRequests { get; set; } = new HashSet<PoRequest>();
    //public virtual ICollection<JobPlanRequest> JobPlanRequests { get; set; } = new HashSet<JobPlanRequest>();
    public virtual ICollection<CarRequest> CarRequests { get; set; } = new HashSet<CarRequest>();
    public virtual ICollection<TravelDeskRequest> TravelDeskRequests { get; set; } = new HashSet<TravelDeskRequest>();
    public virtual ICollection<MenaPayAccessRequest> MenaPayAccessRequests { get; set; } = new HashSet<MenaPayAccessRequest>();
    public virtual ICollection<DomainAccountRequest> DomainAccountRequests { get; set; } = new HashSet<DomainAccountRequest>();
    public virtual ICollection<BiAccessRequest> BiAccessRequests { get; set; } = new HashSet<BiAccessRequest>();
    public virtual ICollection<TosAccessRequest> TosAccessRequests { get; set; } = new HashSet<TosAccessRequest>();
    public virtual ICollection<OracleFusionAccessRequest> OracleFusionAccessRequests { get; set; } = new HashSet<OracleFusionAccessRequest>();

}